services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: foobarhogepiyo
    volumes:
      - book_data:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  book_data: